services:
  back:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: tp_iasc/back
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - ./environments/.env.app.deployed
    volumes:
      - "./logs/container_logs:/usr/src/app/logs"
  front:
    build: 
      context: ./front
      dockerfile: ./Dockerfile
    image: tp_iasc/front
    ports:
      - "3000:3000"
    env_file:
      - ./environments/.env.front.deployed