services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - ./environments/.env.mongo
    volumes:
      - "./data/db:/data/db"
  app:
    build: .
    image: ramiro/tp_iasc
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./environments/.env.app
    volumes:
      - "./logs/container_logs:/usr/src/app/logs"
