services:
  app:
    build: .
    image: ramiro/tp_iasc
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - ./environments/.env.app.deployed
    volumes:
      - "./logs/container_logs:/usr/src/app/logs"
