apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-iasc-back
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tp-iasc-back
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tp-iasc-back
    spec:
      containers:
        - name: tp-iasc-back
          image: nicocollazo/tp-iasc-back
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FRONT_SERVICE_URL
              value: http://127.0.0.1
            - name: STATEMANAGER_SERVICE_URL
              value: http://tp-iasc-state-manager
            - name: TOKEN_SECRET
              value: pescado
            - name: TOKEN_TTL
              value: 20000s
            - name: HEALTHCHECK
              value: "true"
            - name: FRONT_PORT
              value: "3000"
            - name: STATEMANAGER_PORT
              value: "8090"
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-iasc-front
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-iasc-front
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tp-iasc-front
    spec:
      containers:
        - name: tp-iasc-front
          image: nicocollazo/tp-iasc-front
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://127.0.0.1
            - name: REACT_APP_API_PORT
              value: "8080"
            - name: REACT_APP_SOCKET_PORT
              value: "8081"
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-iasc-state-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-iasc-state-manager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tp-iasc-state-manager
    spec:
      containers:
        - name: tp-iasc-state-manager
          image: nicocollazo/tp-iasc-state-manager
          ports:
            - containerPort: 8090
          env:
            - name: PORT
              value: "8090"
            - name: SOCKET_ATTEMPT_TIMEOUTS
              value: "3000"
          imagePullPolicy: Always
