FROM node:16-slim AS builder
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM nginx:1.23-alpine AS server
COPY --from=builder ./app/build /usr/share/nginx/html